### ISSUE TITLE
Alert danger styling

### ISSUE THREAD

**Issue by Quy** [C-Lodder/joomla4-backend-template#87] opened 2020-09-04 18:26 UTC
![alert](https://user-images.githubusercontent.com/368084/92273923-24a28f00-eea1-11ea-8c2e-ead339960ea2.png)

Create a new article.
Leave title blank.
Click Save button.

**Comment by C-Lodder** [comment] 2020-09-05 17:46
Seem to have been caused by https://github.com/joomla/joomla-cms/pull/30294
Will look into this another day

**Comment by C-Lodder** [comment] 2020-10-27 15:32
Fixed in https://github.com/C-Lodder/joomla4-backend-template/commit/25c6bf0db06f291c45355d750589846a94c057f2

**Closed by C-Lodder** 2020-10-27 15:32 UTC
